baseURL = 'https://realdealneil.com/'
languageCode = 'en-us'
theme = 'm10c'
title = "Real Deal's Real Thoughts"

[params]
author = 'Neil Gandhi'
description = 'Making software engineering less painful one day at a time'
avatar = 'avatar-personal.jpg'